In [1]:

from pathlib import Path

import pandas as pd
import numpy as np

DATA_PATH = Path("../data/raw/customer_support_tickets.csv")

df = pd.read_csv(DATA_PATH)

print("Dataset loaded successfully!")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]}")

FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/customer_support_tickets.csv'

In [2]:

from pathlib import Path
import pandas as pd
import numpy as np

DATA_PATH = Path.home() / "ai-support-intelligence" / "data" / "raw" / "customer_support_tickets.csv"

print("File exists:", DATA_PATH.exists())
print("File path:", DATA_PATH)

df = pd.read_csv(DATA_PATH)

print("Dataset loaded successfully!")
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]}")

File exists: True
File path: /home/bohra/ai-support-intelligence/data/raw/customer_support_tickets.csv
Dataset loaded successfully!
Rows: 8,469
Columns: 17

In [4]:
display(df.head(5))

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [5]:

df.info()

print("\nColumn names:")
for column in df.columns:
    print(column)

<class 'pandas.DataFrame'>
RangeIndex: 8469 entries, 0 to 8468
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Ticket ID                     8469 non-null   int64
 1   Customer Name                 8469 non-null   str
 2   Customer Email                8469 non-null   str
 3   Customer Age                  8469 non-null   int64
 4   Customer Gender               8469 non-null   str
 5   Product Purchased             8469 non-null   str
 6   Date of Purchase              8469 non-null   str
 7   Ticket Type                   8469 non-null   str
 8   Ticket Subject                8469 non-null   str
 9   Ticket Description            8469 non-null   str
 10  Ticket Status                 8469 non-null   str
 11  Resolution                    2769 non-null   str
 12  Ticket Priority               8469 non-null   str
 13  Ticket Channel                8469 non-null   str
 14  First Response Time           5650 non-null   str
 15  Time to Resolution            2769 non-null   str
 16  Customer Satisfaction Rating  2769 non-null   float64
dtypes: float64(1), int64(2), str(14)
memory usage: 1.1 MB

Column names:
Ticket ID
Customer Name
Customer Email
Customer Age
Customer Gender
Product Purchased
Date of Purchase
Ticket Type
Ticket Subject
Ticket Description
Ticket Status
Resolution
Ticket Priority
Ticket Channel
First Response Time
Time to Resolution
Customer Satisfaction Rating

In [6]:

quality_report = pd.DataFrame({
    "data_type": df.dtypes.astype(str),
    "missing_count": df.isna().sum(),
    "missing_percent": (df.isna().mean() * 100).round(2),
    "unique_values": df.nunique()
})

display(quality_report)

print("Duplicate rows:", df.duplicated().sum())

,data_type,missing_count,missing_percent,unique_values
Ticket ID,int64,0,0.00,8469
Customer Name,str,0,0.00,8028
Customer Email,str,0,0.00,8320
Customer Age,int64,0,0.00,53
Customer Gender,str,0,0.00,3
Product Purchased,str,0,0.00,42
Date of Purchase,str,0,0.00,730
Ticket Type,str,0,0.00,5
Ticket Subject,str,0,0.00,16
Ticket Description,str,0,0.00,8077
Ticket Status,str,0,0.00,3
Resolution,str,5700,67.30,2769
Ticket Priority,str,0,0.00,4
Ticket Channel,str,0,0.00,4
First Response Time,str,2819,33.29,5470
Time to Resolution,str,5700,67.30,2728
Customer Satisfaction Rating,float64,5700,67.30,5

Duplicate rows: 0

In [7]:

for column in df.columns:
    print(f"\n--- {column} ---")
    print(df[column].value_counts(dropna=False).head(10))

--- Ticket ID ---
Ticket ID
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
Name: count, dtype: int64

--- Customer Name ---
Customer Name
Michael Garcia       5
James Smith          5
David Smith          4
Steven Johnson       4
Christopher Jones    4
Joseph Brown         4
Daniel Williams      4
Rebecca Smith        4
Jennifer Smith       4
Michael White        4
Name: count, dtype: int64

--- Customer Email ---
Customer Email
asmith@example.com              4
bsmith@example.com              4
drodriguez@example.com          3
asmith@example.org              3
hsmith@example.org              3
elizabethjenkins@example.com    3
michael41@example.net           3
rodriguezeric@example.net       3
david40@example.org             2
bevans@example.org              2
Name: count, dtype: int64

--- Customer Age ---
Customer Age
52    186
56    182
27    180
24    180
34    177
59    177
44    173
20    173
48    172
63    171
Name: count, dtype: int64

--- Customer Gender ---
Customer Gender
Male      2896
Female    2887
Other     2686
Name: count, dtype: int64

--- Product Purchased ---
Product Purchased
Canon EOS              240
GoPro Hero             228
Nest Thermostat        225
Philips Hue Lights     221
Amazon Echo            221
LG Smart TV            219
Sony Xperia            217
Roomba Robot Vacuum    216
LG OLED                213
Apple AirPods          213
Name: count, dtype: int64

--- Date of Purchase ---
Date of Purchase
2020-10-21    24
2021-11-05    24
2021-02-01    23
2021-07-04    23
2021-10-24    22
2021-11-21    22
2021-01-03    22
2021-03-27    22
2021-08-16    20
2020-09-26    20
Name: count, dtype: int64

--- Ticket Type ---
Ticket Type
Refund request          1752
Technical issue         1747
Cancellation request    1695
Product inquiry         1641
Billing inquiry         1634
Name: count, dtype: int64

--- Ticket Subject ---
Ticket Subject
Refund request           576
Software bug             574
Product compatibility    567
Delivery problem         561
Hardware issue           547
Battery life             542
Network problem          539
Installation support     530
Product setup            529
Payment issue            526
Name: count, dtype: int64

--- Ticket Description ---
Ticket Description
I'm having an issue with the {product_purchased}. Please assist. I need assistance as soon as possible because it's affecting my work and productivity.                                                  25
I'm having an issue with the {product_purchased}. Please assist. I'm concerned about the security of my {product_purchased} and would like to ensure that my data is safe.                               25
I'm having an issue with the {product_purchased}. Please assist. This problem started occurring after the recent software update. I haven't made any other changes to the device.                        25
I'm having an issue with the {product_purchased}. Please assist. I've noticed a peculiar error message popping up on my {product_purchased} screen. It says '{error_message}'. What does it mean?        24
I'm having an issue with the {product_purchased}. Please assist. I've already contacted customer support multiple times, but the issue remains unresolved.                                               24
I'm having an issue with the {product_purchased}. Please assist. I've performed a factory reset on my {product_purchased}, hoping it would resolve the problem, but it didn't help.                      23
I'm having an issue with the {product_purchased}. Please assist. I'm unable to find the option to perform the desired action in the {product_purchased}. Could you please guide me through the steps?    20
I'm having an issue with the {product_purchased}. Please assist. The issue I'm facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.                                 20
I'm having an issue with the {product_purchased}. Please assist. I've noticed that the issue occurs consistently when I use a specific feature or application on my {product_purchased}.                 17
I'm having an issue with the {product_purchased}. Please assist. I've checked for software updates, and my {product_purchased} is already running the latest version.                                    17
Name: count, dtype: int64

--- Ticket Status ---
Ticket Status
Pending Customer Response    2881
Open                         2819
Closed                       2769
Name: count, dtype: int64

--- Resolution ---
Resolution
NaN                                                     5700
Case maybe show recently my computer follow.               1
Try capital clearly never color toward story.              1
West decision evidence bit.                                1
Measure tonight surface feel forward.                      1
Measure there house management pick knowledge trade.       1
Officer moment world sing parent available.                1
Seek evidence book collection catch.                       1
Wish mouth build resource though.                          1
Soldier we such inside.                                    1
Name: count, dtype: int64

--- Ticket Priority ---
Ticket Priority
Medium      2192
Critical    2129
High        2085
Low         2063
Name: count, dtype: int64

--- Ticket Channel ---
Ticket Channel
Email           2143
Phone           2132
Social media    2121
Chat            2073
Name: count, dtype: int64

--- First Response Time ---
First Response Time
NaN                    2819
2023-06-01 01:21:19       3
2023-06-01 15:21:42       3
2023-06-01 20:45:39       3
2023-06-01 17:46:49       2
2023-06-01 12:05:51       2
2023-06-01 19:03:53       2
2023-06-01 16:57:26       2
2023-06-01 21:00:57       2
2023-05-31 23:52:47       2
Name: count, dtype: int64

--- Time to Resolution ---
Time to Resolution
NaN                    5700
2023-06-01 17:14:42       3
2023-06-01 10:17:08       2
2023-06-01 10:40:04       2
2023-06-01 21:20:39       2
2023-06-01 16:44:47       2
2023-06-01 13:07:31       2
2023-06-01 20:14:34       2
2023-06-01 14:53:35       2
2023-06-01 20:03:05       2
Name: count, dtype: int64

--- Customer Satisfaction Rating ---
Customer Satisfaction Rating
NaN    5700
3.0     580
1.0     553
2.0     549
5.0     544
4.0     543
Name: count, dtype: int64

In [8]:

print("Dataset columns:")
print(df.columns.tolist())

Dataset columns:
['Ticket ID', 'Customer Name', 'Customer Email', 'Customer Age', 'Customer Gender', 'Product Purchased', 'Date of Purchase', 'Ticket Type', 'Ticket Subject', 'Ticket Description', 'Ticket Status', 'Resolution', 'Ticket Priority', 'Ticket Channel', 'First Response Time', 'Time to Resolution', 'Customer Satisfaction Rating']

In [9]:

# Check the distribution of ticket categories
print("Ticket Type counts:")
display(df["Ticket Type"].value_counts(dropna=False))

print("\nTicket Type percentages:")
display(
    (df["Ticket Type"].value_counts(normalize=True, dropna=False) * 100)
    .round(2)
)

print("\nMissing Ticket Type values:", df["Ticket Type"].isna().sum())

Ticket Type counts:

Ticket Type
Refund request          1752
Technical issue         1747
Cancellation request    1695
Product inquiry         1641
Billing inquiry         1634
Name: count, dtype: int64

Ticket Type percentages:

Ticket Type
Refund request          20.69
Technical issue         20.63
Cancellation request    20.01
Product inquiry         19.38
Billing inquiry         19.29
Name: proportion, dtype: float64

Missing Ticket Type values: 0

In [10]:

display(
    df[["Ticket Type", "Ticket Subject", "Ticket Description"]]
    .sample(10, random_state=42)
)

,Ticket Type,Ticket Subject,Ticket Description
4830,Refund request,Product setup,I'm having an issue with the {product_purchase...
7075,Product inquiry,Battery life,I'm having trouble connecting my {product_purc...
4715,Billing inquiry,Refund request,I'm having an issue with the {product_purchase...
2022,Billing inquiry,Peripheral compatibility,I'm having an issue with the {product_purchase...
676,Refund request,Peripheral compatibility,I'm having an issue with the {product_purchase...
2283,Refund request,Refund request,I've encountered a data loss issue with my {pr...
5076,Product inquiry,Software bug,I'm having an issue with the {product_purchase...
2476,Refund request,Installation support,I'm having an issue with the {product_purchase...
6847,Refund request,Hardware issue,I'm encountering a software bug in the {produc...
511,Product inquiry,Battery life,I'm having an issue with the {product_purchase...

In [11]:

print("Ticket categories:")
display(df["Ticket Type"].value_counts(dropna=False))

print("\nUnique ticket categories:", df["Ticket Type"].nunique())
print("Missing ticket types:", df["Ticket Type"].isna().sum())

Ticket categories:

Ticket Type
Refund request          1752
Technical issue         1747
Cancellation request    1695
Product inquiry         1641
Billing inquiry         1634
Name: count, dtype: int64

Unique ticket categories: 5
Missing ticket types: 0

In [12]:

print("Unique subjects:", df["Ticket Subject"].nunique())
print("Unique descriptions:", df["Ticket Description"].nunique())

display(
    df[["Ticket Type", "Ticket Subject", "Ticket Description"]]
    .head(10)
    .to_string(index=False)
)

Unique subjects: 16
Unique descriptions: 8077

'         Ticket Type           Ticket Subject                                                                                                                                                                                                                                                                                                                                      Ticket Description\n     Technical issue            Product setup                                                      I\'m having an issue with the {product_purchased}. Please assist.\\n\\nYour billing zip code is: 71701.\\n\\nWe appreciate that you have requested a website address.\\n\\nPlease double check your email address. I\'ve tried troubleshooting steps mentioned in the user manual, but the issue persists.\n     Technical issue Peripheral compatibility                                                        I\'m having an issue with the {product_purchased}. Please assist.\\n\\nIf you need to change an existing product.\\n\\nI\'m having an issue with the {product_purchased}. Please assist.\\n\\nIf The issue I\'m facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.\n     Technical issue          Network problem                                                                   I\'m facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn\'t respond.\\n\\n1.8.3 I really I\'m using the original charger that came with my {product_purchased}, but it\'s not charging properly.\n     Billing inquiry           Account access                                                                                I\'m having an issue with the {product_purchased}. Please assist.\\n\\nIf you have a problem you\'re interested in and I\'d love to see this happen, please check out the Feedback. I\'ve already contacted customer support multiple times, but the issue remains unresolved.\n     Billing inquiry                Data loss        I\'m having an issue with the {product_purchased}. Please assist.\\n\\n\\nNote: The seller is not responsible for any damages arising out of the delivery of the battleground game. Please have the game in good condition and shipped to you I\'ve noticed a sudden decrease in battery life on my {product_purchased}. It used to last much longer.\nCancellation request            Payment issue                                                          I\'m facing a problem with my {product_purchased}. The {product_purchased} is not turning on. It was working fine until yesterday, but now it doesn\'t respond. To remove the new {product_purch I\'ve checked for any available software updates for my {product_purchased}, but there are none.\n     Product inquiry           Refund request I\'m unable to access my {product_purchased} account. It keeps displaying an \'Invalid Credentials\' error, even though I\'m using the correct login information. How can I regain access to my account?\\n\\nSolution 1 I\'m unable to find the option to perform the desired action in the {product_purchased}. Could you please guide me through the steps?\n      Refund request             Battery life            I\'m having an issue with the {product_purchased}. Please assist. (Thanks) I will contact all my suppliers and confirm.\\n\\nPlease try and find out whether their inventory is currently stocked, or any other reason. I am I\'ve performed a factory reset on my {product_purchased}, hoping it would resolve the problem, but it didn\'t help.\n     Technical issue     Installation support   I\'m having an issue with the {product_purchased}. Please assist. Thank you.\\n\\n{product_purchased} is not the exact type you might prefer, they use the exact same method for different uses. Please help I\'ve recently updated the firmware of my {product_purchased}, and the issue started happening afterward. Could it be related to the update?\n      Refund request            Payment issue                                       My {product_purchased} is making strange noises and not functioning properly. I suspect there might be a hardware issue. Can you please help me with this?\\n\\n} If we can, please send a "request" to dav The issue I\'m facing is intermittent. Sometimes it works fine, but other times it acts up unexpectedly.'

In [13]:

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# 1. Prepare the input text and target label
X = (
    df["Ticket Subject"].fillna("").astype(str)
    + " "
    + df["Ticket Description"].fillna("").astype(str)
)

y = df["Ticket Type"]

# Exclude rows with missing target labels
valid = y.notna()
X = X[valid]
y = y[valid]

# 2. Split data before training
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training examples:", len(X_train))
print("Testing examples:", len(X_test))

# 3. Build the ML pipeline
model = Pipeline([
    (
        "tfidf",
        TfidfVectorizer(
            lowercase=True,
            ngram_range=(1, 2),
            max_features=50000,
            sublinear_tf=True
        )
    ),
    (
        "classifier",
        LogisticRegression(
            max_iter=1000,
            random_state=42
        )
    )
])

# 4. Train the model
model.fit(X_train, y_train)

# 5. Evaluate on unseen test data
y_pred = model.predict(X_test)

print(f"\nAccuracy: {accuracy_score(y_test, y_pred):.4f}")
print("\nClassification report:")
print(classification_report(y_test, y_pred, zero_division=0))

Training examples: 6775
Testing examples: 1694

Accuracy: 0.2072

Classification report:
                      precision    recall  f1-score   support

     Billing inquiry       0.19      0.17      0.18       327
Cancellation request       0.18      0.16      0.17       339
     Product inquiry       0.21      0.19      0.20       328
      Refund request       0.23      0.26      0.24       351
     Technical issue       0.22      0.26      0.24       349

            accuracy                           0.21      1694
           macro avg       0.21      0.21      0.20      1694
        weighted avg       0.21      0.21      0.21      1694

In [17]:

from sklearn.base import clone
from sklearn.metrics import accuracy_score, f1_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

# Keep exactly the same train/test split for a fair comparison
text_variants = {
    "Subject only": (
        df.loc[X_train.index, "Ticket Subject"].fillna("").astype(str),
        df.loc[X_test.index, "Ticket Subject"].fillna("").astype(str),
    ),
    "Description only": (
        df.loc[X_train.index, "Ticket Description"].fillna("").astype(str),
        df.loc[X_test.index, "Ticket Description"].fillna("").astype(str),
    ),
    "Subject + description": (X_train, X_test),
}

results = []

for name, (train_text, test_text) in text_variants.items():
    experiment = Pipeline([
        ("tfidf", TfidfVectorizer(
            lowercase=True,
            ngram_range=(1, 2),
            max_features=50000,
            sublinear_tf=True
        )),
        ("classifier", LogisticRegression(
            max_iter=1000,
            random_state=42
        ))
    ])

    experiment.fit(train_text, y_train)
    predictions = experiment.predict(test_text)

    results.append({
        "Input": name,
        "Accuracy": round(accuracy_score(y_test, predictions), 4),
        "Macro F1": round(
            f1_score(y_test, predictions, average="macro"),
            4
        )
    })

results_df = pd.DataFrame(results)
display(results_df)

                   Input  Accuracy  Macro F1
0           Subject only    0.1818    0.1783
1       Description only    0.1989    0.1972
2  Subject + description    0.2072    0.2046

In [18]:

subject_category = pd.crosstab(
    df["Ticket Subject"],
    df["Ticket Type"],
    normalize="index"
).round(2)

display(subject_category)

Ticket Type,Billing inquiry,Cancellation request,Product inquiry,Refund request,Technical issue
Ticket Subject,,,,,
Account access,0.20,0.18,0.21,0.21,0.19
Battery life,0.20,0.19,0.19,0.22,0.21
Cancellation request,0.17,0.21,0.17,0.22,0.22
Data loss,0.18,0.23,0.19,0.20,0.20
Delivery problem,0.20,0.20,0.19,0.19,0.21
Display issue,0.19,0.22,0.17,0.21,0.22
Hardware issue,0.18,0.20,0.19,0.24,0.19
Installation support,0.20,0.19,0.19,0.22,0.20
Network problem,0.18,0.19,0.21,0.20,0.23
Payment issue,0.20,0.21,0.17,0.20,0.21
Peripheral compatibility,0.19,0.21,0.19,0.21,0.20
Product compatibility,0.22,0.17,0.21,0.19,0.21
Product recommendation,0.18,0.19,0.21,0.21,0.21
Product setup,0.20,0.20,0.19,0.20,0.21
Refund request,0.17,0.22,0.21,0.21,0.19
Software bug,0.21,0.19,0.20,0.20,0.21